# docker build -t timescaledb:2.6.1 .
# docker run -d --name timescaledb -e POSTGRES_PASSWORD=mydatabasepassword -p 10000:5432 timescaledb:2.6.1 -c ssl=on -c ssl_cert_file=/etc/certs/server-cert.pem -c ssl_key_file=/etc/certs/server-key.pem -c ssl_ca_file=/etc/certs/ca.pem

FROM timescale/timescaledb:2.6.1-pg14

RUN mkdir -p /etc/certs
COPY ./certificates/ca.pem /etc/certs/ca.pem
COPY ./certificates/server-key.pem /etc/certs/server-key.pem
COPY ./certificates/server-cert.pem /etc/certs/server-cert.pem
RUN chmod 600 /etc/certs/*
RUN chown postgres:postgres /etc/certs/*
